[colors]
foreground = "#dcdccc"
background = "#4f4f4f"
cursor_bg = "#dcdccc"
cursor_border = "#dcdccc"
cursor_fg = "#4f4f4f"
selection_bg = "#4e5c5d"
selection_fg = "#dcdccc"
split = "#8cd0d3"
compose_cursor = "#afd8af"
scrollbar_thumb = "#5f5f5f"

ansi = ["#3f3f3f", "#94bff3", "#cc9393", "#8cd0d3", "#8cd0d3", "#f0dfaf", "#f0dfaf", "#656555"]
brights = ["#3f3f3f", "#94bff3", "#cc9393", "#8cd0d3", "#8cd0d3", "#f0dfaf", "#f0dfaf", "#dcdccc"]

[colors.tab_bar]
inactive_tab_edge = "#2b2b2b"
background = "#4f4f4f"

[colors.tab_bar.active_tab]
fg_color = "#2b2b2b"
bg_color = "#8cd0d3"

[colors.tab_bar.inactive_tab]
fg_color = "#6f6f6f"
bg_color = "#5f5f5f"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#8cd0d3"
bg_color = "#5f5f5f"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#8cd0d3"
bg_color = "#4f4f4f"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#8cd0d3"
bg_color = "#4f4f4f"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_zenburn"