[colors]
foreground = "#dcdccc"
background = "#4f4f4f"
cursor_bg = "#dcdccc"
cursor_border = "#dcdccc"
cursor_fg = "#4f4f4f"
selection_bg = "#485985"
selection_fg = "#dcdccc"
split = "#8cd0d3"
compose_cursor = "#dfaf8f"
scrollbar_thumb = "#5f5f5f"

ansi = ["#3f3f3f", "#cc9393", "#4f6f4f", "#f0dfaf", "#8cd0d3", "#dc8cc3", "#93e0e3", "#656555"]
brights = ["#3f3f3f", "#cc9393", "#4f6f4f", "#f0dfaf", "#8cd0d3", "#dc8cc3", "#93e0e3", "#dcdccc"]

[colors.tab_bar]
inactive_tab_edge = "#2b2b2b"
background = "#4f4f4f"

[colors.tab_bar.active_tab]
fg_color = "#2b2b2b"
bg_color = "#8cd0d3"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#5f5f5f"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#8cd0d3"
bg_color = "#5f5f5f"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#8cd0d3"
bg_color = "#4f4f4f"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#8cd0d3"
bg_color = "#4f4f4f"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_zenburn"