# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night Zenburn
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_zenburn.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#4f4f4f'
foreground = '#dcdccc'

#[colors.cursor]
#cursor = '#dcdccc'
#text = '#4f4f4f'

# Normal colors
[colors.normal]
black = '#3f3f3f'
red = '#94bff3'
green = '#cc9393'
yellow = '#8cd0d3'
blue = '#8cd0d3'
magenta = '#f0dfaf'
cyan = '#f0dfaf'
white = '#fffffd'

# Bright colors
[colors.bright]
black = '#3f3f3f'
red = '#a4cdff'
green = '#e29d9d'
yellow = '#74e3e8'
blue = '#74e3e8'
magenta = '#faedcd'
cyan = '#faedcd'
white = '#dcdccc'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#afd8af'

[[colors.indexed_colors]]
index = 17
color = '#8c5353'

