# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#4f4f4f'
foreground = '#dcdccc'

#[colors.cursor]
#cursor = '#dcdccc'
#text = '#4f4f4f'

# Normal colors
[colors.normal]
black = '#3f3f3f'
red = '#cc9393'
green = '#4f6f4f'
yellow = '#f0dfaf'
blue = '#8cd0d3'
magenta = '#dc8cc3'
cyan = '#93e0e3'
white = '#656555'

# Bright colors
[colors.bright]
black = '#3f3f3f'
red = '#cc9393'
green = '#4f6f4f'
yellow = '#f0dfaf'
blue = '#8cd0d3'
magenta = '#dc8cc3'
cyan = '#93e0e3'
white = '#dcdccc'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#dfaf8f'

[[colors.indexed_colors]]
index = 17
color = '#8c5353'

