# -----------------------------------------------------------------------------
# TokyoNight Alacritty Colors
# Theme: Tokyo Night Zenburn
# Upstream: https://github.com/folke/tokyonight.nvim/raw/main/extras/alacritty/tokyonight_zenburn.toml
# -----------------------------------------------------------------------------

# Default colors
[colors.primary]
background = '#4f4f4f'
foreground = '#dcdccc'

# Normal colors
[colors.normal]
black = '#3f3f3f'
red = '#94bff3'
green = '#cc9393'
yellow = '#8cd0d3'
blue = '#8cd0d3'
magenta = '#f0dfaf'
cyan = '#dfaf8f'
white = '#fffffd'

# Bright colors
[colors.bright]
black = '#3f3f3f'
red = '#a4cdff'
green = '#e29d9d'
yellow = '#74e3e8'
blue = '#74e3e8'
magenta = '#faedcd'
cyan = '#efbc9b'
white = '#dcdccc'
