[[themes]]
name = "Tokyo Night Zenburn"
[themes.palette]
background = "#2b2b2b"
foreground = "#fffffd"
black = "#3f3f3f"
red = "#94bff3"
green = "#cc9393"
yellow = "#8cd0d3"
blue = "#8cd0d3"
magenta = "#f0dfaf"
cyan = "#f0dfaf"
white = "${white}"
bright_black = "#4f4f4f"
bright_red = "#8c5353"
bright_green = "#7cb8bb"
bright_yellow = "#afd8af"
bright_blue = "#94bff3"
bright_magenta = "#d0bf8f"
bright_cyan = "#7cb8bb"
bright_white = "#dcdccc"
