local util = require("tokyonight.util")

local zenburn_fg_m2 = "#dfdfdf"
local zenburn_fg_m1 = "#656555"
local zenburn_fg_m05 = "#989890"
local zenburn_fg = "#dcdccc"
local zenburn_fg_p1 = "#ffffef"
local zenburn_fg_p2 = "#fffffd"
local zenburn_bg_m2 = "#000000"
local zenburn_bg_m1 = "#2b2b2b"
local zenburn_bg_m08 = "#303030"
local zenburn_bg_m05 = "#383838"
local zenburn_bg = "#3f3f3f"
local zenburn_bg_p05 = "#494949"
local zenburn_bg_p1 = "#4f4f4f"
local zenburn_bg_p2 = "#5f5f5f"
local zenburn_bg_p3 = "#6f6f6f"
local zenburn_bg_p4 = "#8f8f8f"
local zenburn_red_m6 = "#6c3333"
local zenburn_red_m5 = "#7c4343"
local zenburn_red_m4 = "#8c5353"
local zenburn_red_m3 = "#9c6363"
local zenburn_red_m2 = "#ac7373"
local zenburn_red_m1 = "#bc8383"
local zenburn_red = "#cc9393"
local zenburn_red_p1 = "#dca3a3"
local zenburn_red_p2 = "#ecb3b3"
local zenburn_red_p3 = "#9c6363"
local zenburn_red_p4 = "#8c5353"
local zenburn_orange = "#dfaf8f"
local zenburn_yellow_m2 = "#d0bf8f"
local zenburn_yellow_m1 = "#e0cf9f"
local zenburn_yellow = "#f0dfaf"
local zenburn_green_m5 = "#2f4f2f"
local zenburn_green_m4 = "#3f5f3f"
local zenburn_green_m3 = "#4f6f4f"
local zenburn_green_m2 = "#5f7f5f"
local zenburn_green_m1 = "#6f8f6f"
local zenburn_green = "#7f9f7f"
local zenburn_green_p1 = "#8fb28f"
local zenburn_green_p2 = "#9fc59f"
local zenburn_green_p3 = "#afd8af"
local zenburn_green_p4 = "#bfebbf"
local zenburn_cyan = "#93e0e3"
local zenburn_blue_p4 = "#c0bed1"
local zenburn_blue_p3 = "#bde0f3"
local zenburn_blue_p2 = "#ace0e3"
local zenburn_blue_p1 = "#94bff3"
local zenburn_blue = "#8cd0d3"
local zenburn_blue_m1 = "#7cb8bb"
local zenburn_blue_m2 = "#6ca0a3"
local zenburn_blue_m3 = "#5c888b"
local zenburn_blue_m4 = "#4c7073"
local zenburn_blue_m5 = "#366060"
local zenburn_magenta = "#dc8cc3"

---@type Palette
local ret = {
  none = "NONE",
  bg_dark = zenburn_bg_m1, --
  bg_dark1 = zenburn_bg_m08, --
  bg = zenburn_bg_p1, --
  bg_highlight = zenburn_bg_p2, --
  terminal_black = zenburn_bg, --
  fg = zenburn_fg, --
  fg_dark = zenburn_fg_p2, --
  fg_gutter = zenburn_fg_m05,
  dark3 = zenburn_bg_p3,
  comment = zenburn_green, --
  dark5 = zenburn_bg_m2, -- Conceal/CursorLineNr/WhichKeyValue
  blue0 = zenburn_blue_m4, --
  blue = zenburn_blue, --
  cyan = zenburn_yellow, -- keyword
  blue1 = zenburn_blue_p1, --
  blue2 = zenburn_blue_p2,
  blue5 = zenburn_blue_m1,
  blue6 = zenburn_blue_m3, --
  blue7 = zenburn_blue_m5,
  purple = zenburn_yellow_m1, -- @keyword for keywords not in other categories
  magenta2 = zenburn_yellow_m2, -- TSNodeKey
  magenta = zenburn_yellow, -- Identifier/Statement
  orange = zenburn_green_p3, -- IncSearch bg/Constant/Debug
  yellow = zenburn_blue, -- string.doc/variable
  green = zenburn_red, -- used for strings
  green1 = zenburn_blue_m1, -- @property/@variable.member
  green2 = "#2f4f2f",
  teal = "#4c7073", --
  red = zenburn_blue_p1, -- variable and module builtin
  red1 = "#8c5353", --
  git = {
    change = util.blend(zenburn_blue, "ee", zenburn_bg_p1),
    add = util.blend(zenburn_green, "ee", zenburn_bg_p1),
    delete = util.blend(zenburn_red, "dd", zenburn_bg_p1),
  },
  gitSigns = {
    change = util.blend(zenburn_blue, "66", zenburn_bg_p1),
    add = util.blend(zenburn_green, "66", zenburn_bg_p1),
    delete = util.blend(zenburn_red, "aa", zenburn_bg_p1),
  },
}
return ret
