attribute = { fg = "#f0dfaf" }
comment = { fg = "#7f9f7f", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#8cd0d3" }
constant = { fg = "#afd8af" }
"constant.builtin" = { fg = "#94bff3" }
"constant.builtin.boolean" = { fg = "#afd8af" }
"constant.character" = { fg = "#cc9393" }
"constant.character.escape" = { fg = "#f0dfaf" }
"constant.numeric" = { fg = "#afd8af" }
"constant.numeric.float" = { fg = "#afd8af" }
"constant.numeric.integer" = { fg = "#afd8af" }
constructor = { fg = "#94bff3" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#88c7ca" }
"diff.delta.moved" = { fg = "#8cd0d3" }
"diff.minus" = { fg = "#bb8a8a" }
"diff.plus" = { fg = "#7c9a7c" }
error = { fg = "#8c5353" }
function = { fg = "#8cd0d3" }
"function.builtin" = { fg = "#94bff3" }
"function.macro" = { fg = "#f0dfaf" }
"function.method" = { fg = "#8cd0d3" }
"function.special" = { fg = "#f0dfaf" }
hint = { fg = "#4c7073" }
info = { fg = "#ace0e3" }
keyword = { fg = "#e0cf9f", modifiers = ["italic"] }
"keyword.control" = { fg = "#f0dfaf" }
"keyword.control.conditional" = { fg = "#f0dfaf" }
"keyword.control.exception" = { fg = "#f0dfaf" }
"keyword.control.repeat" = { fg = "#f0dfaf" }
"keyword.control.return" = { fg = "#e0cf9f", modifiers = ["italic"] }
"keyword.directive" = { fg = "#f0dfaf" }
"keyword.function" = { fg = "#f0dfaf" }
"keyword.operator" = { fg = "#f0dfaf" }
label = { fg = "#8cd0d3" }
"markup.bold" = { fg = "#dcdccc", modifiers = ["bold"] }
"markup.heading" = { fg = "#8cd0d3", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#2b2b2b", fg = "#dcdccc" }
"markup.heading.hover" = { bg = "#616154" }
"markup.italic" = { fg = "#dcdccc", modifiers = ["italic"] }
"markup.link" = { fg = "#4c7073" }
"markup.link.label" = { fg = "#94bff3" }
"markup.link.text" = { fg = "#4c7073" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#7cb8bb" }
"markup.normal.completion" = { fg = "#7f9f7f" }
"markup.normal.hover" = { fg = "#fffffd" }
"markup.raw" = { fg = "#cc9393" }
"markup.raw.inline" = { bg = "#3f3f3f", fg = "#8cd0d3" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#f0dfaf" }
operator = { fg = "#7cb8bb" }
special = { fg = "#94bff3" }
string = { fg = "#cc9393" }
"string.regexp" = { fg = "#5c888b" }
"string.special" = { fg = "#94bff3" }
tag = { fg = "#f0dfaf" }
type = { fg = "#94bff3" }
"type.builtin" = { fg = "#86a9d2" }
"type.enum" = { fg = "#94bff3" }
"type.enum.variant" = { fg = "#afd8af" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#dcdccc", fg = "#4f4f4f" }
"ui.cursor.match" = { fg = "#afd8af", modifiers = ["bold"] }
"ui.linenr" = { fg = "#656555" }
"ui.linenr.select" = { fg = "#afd8af", modifiers = ["bold"] }
"ui.menu" = { bg = "#2b2b2b", fg = "#dcdccc" }
"ui.menu.scroll" = { bg = 3421235, fg = 6645077 }
"ui.menu.selected" = { bg = "#616154" }
"ui.popup" = { bg = "#2b2b2b", fg = "#86a9d2" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#2b2b2b", fg = "#fffffd" }
"ui.statusline.inactive" = { bg = "#2b2b2b", fg = "#656555" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#4f4f4f", fg = "#dcdccc" }
"ui.text.focus" = { bg = "#4e5c5d" }
"ui.text.inactive" = { fg = "#7f9f7f", modifiers = ["italic"] }
"ui.text.info" = { bg = "#2b2b2b", fg = "#dcdccc" }
"ui.virtual.inlay-hint" = { bg = "#4f5253", fg = "#4c7073" }
"ui.window" = { fg = "#3f3f3f", modifiers = ["bold"] }
variable = { fg = "#dcdccc" }
"variable.builtin" = { fg = "#94bff3" }
"variable.other.member" = { fg = "#7cb8bb" }
"variable.parameter" = { fg = "#8cd0d3" }
warning = { fg = "#8cd0d3" }

[palette]
bg = "#4f4f4f"
bg_dark = "#2b2b2b"
bg_dark1 = "#303030"
bg_float = "#2b2b2b"
bg_highlight = "#5f5f5f"
bg_popup = "#2b2b2b"
bg_search = "#4c7073"
bg_sidebar = "#2b2b2b"
bg_statusline = "#2b2b2b"
bg_visual = "#4e5c5d"
black = "#3f3f3f"
blue = "#8cd0d3"
blue0 = "#4c7073"
blue1 = "#94bff3"
blue2 = "#ace0e3"
blue5 = "#7cb8bb"
blue6 = "#5c888b"
blue7 = "#366060"
border = "#3f3f3f"
border_highlight = "#86a9d2"
comment = "#7f9f7f"
cyan = "#f0dfaf"
dark3 = "#6f6f6f"
dark5 = "#000000"
"diff.add" = "#4a4f4a"
"diff.change" = "#4b5252"
"diff.delete" = "#585050"
"diff.text" = "#366060"
error = "#8c5353"
fg = "#dcdccc"
fg_dark = "#fffffd"
fg_float = "#dcdccc"
fg_gutter = "#656555"
fg_sidebar = "#fffffd"
"git.add" = "#7c9a7c"
"git.change" = "#88c7ca"
"git.delete" = "#bb8a8a"
"git.ignore" = "#6f6f6f"
"gitSigns.add" = "#626f62"
"gitSigns.change" = "#678384"
"gitSigns.delete" = "#a27c7c"
green = "#cc9393"
green1 = "#7cb8bb"
green2 = "#2f4f2f"
hint = "#4c7073"
info = "#ace0e3"
magenta = "#f0dfaf"
magenta2 = "#d0bf8f"
orange = "#afd8af"
purple = "#e0cf9f"
rainbow = "#8cd0d3"
"rainbow.2" = "#8cd0d3"
"rainbow.3" = "#cc9393"
"rainbow.4" = "#4c7073"
"rainbow.5" = "#f0dfaf"
"rainbow.6" = "#e0cf9f"
"rainbow.7" = "#afd8af"
"rainbow.8" = "#94bff3"
red = "#94bff3"
red1 = "#8c5353"
teal = "#4c7073"
"terminal.black" = "#3f3f3f"
"terminal.black_bright" = "#3f3f3f"
"terminal.blue" = "#8cd0d3"
"terminal.blue_bright" = "#74e3e8"
"terminal.cyan" = "#f0dfaf"
"terminal.cyan_bright" = "#faedcd"
"terminal.green" = "#cc9393"
"terminal.green_bright" = "#e29d9d"
"terminal.magenta" = "#f0dfaf"
"terminal.magenta_bright" = "#faedcd"
"terminal.red" = "#94bff3"
"terminal.red_bright" = "#a4cdff"
"terminal.white" = "#fffffd"
"terminal.white_bright" = "#dcdccc"
"terminal.yellow" = "#8cd0d3"
"terminal.yellow_bright" = "#74e3e8"
terminal_black = "#3f3f3f"
todo = "#8cd0d3"
warning = "#8cd0d3"
yellow = "#8cd0d3"