[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#fffffd", italic = true }

# Hovered
hovered         = { bg = "#5f5f5f" }
preview_hovered = { bg = "#5f5f5f" }

# Find
find_keyword  = { fg = "#2b2b2b", bg = "#afd8af", bold = true }
find_position = { fg = "#ace0e3", bg = "#585e5e", bold = true }

# Marker
marker_copied   = { fg = "#7cb8bb", bg = "#7cb8bb" }
marker_cut      = { fg = "#94bff3", bg = "#94bff3" }
marker_marked   = { fg = "#f0dfaf", bg = "#f0dfaf" }
marker_selected = { fg = "#8cd0d3", bg = "#8cd0d3" }

# Tab
tab_active   = { fg = "#dcdccc", bg = "#5f5f5f" }
tab_inactive = { fg = "#656555", bg = "#4f4f4f" }
tab_width    = 1

# Count
count_copied   = { fg = "#dcdccc", bg = "#2f4f2f" }
count_cut      = { fg = "#dcdccc", bg = "#8c5353" }
count_selected = { fg = "#dcdccc", bg = "#4c7073" }

# Border
border_symbol = "│"
border_style  = { fg = "#86a9d2" }

[mode]
normal_main = { fg = "#3f3f3f", bg = "#8cd0d3", bold = true }
normal_alt  = { fg = "#8cd0d3", bg = "#656555" }

select_main = { fg = "#3f3f3f", bg = "#f0dfaf", bold = true }
select_alt  = { fg = "#f0dfaf", bg = "#656555" }

unset_main  = { fg = "#3f3f3f", bg = "#e0cf9f", bold = true }
unset_alt   = { fg = "#e0cf9f", bg = "#656555" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#656555", bg = "#656555" }

# Progress
progress_label  = { fg = "#fffffd", bold = true }
progress_normal = { fg = "#4f4f4f" }
progress_error  = { fg = "#94bff3" }

# Permissions
perm_type  = { fg = "#8cd0d3" }
perm_read  = { fg = "#8cd0d3" }
perm_write = { fg = "#94bff3" }
perm_exec  = { fg = "#cc9393" }
perm_sep   = { fg = "#3f3f3f" }

[pick]
border   = { fg = "#86a9d2" }
active   = { fg = "#dcdccc",  bg = "#4e5c5d" }
inactive = { fg = "#dcdccc" }

# Input
[input]
border   = { fg = "#ace0e3" }
title    = { fg = "#ace0e3" }
value    = { fg = "#e0cf9f" }
selected = { bg = "#4e5c5d" }

# Completion
[completion]
border   = { fg = "#ace0e3" }
active   = { fg = "#dcdccc", bg = "#4e5c5d" }
inactive = { fg = "#dcdccc" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#86a9d2" }
title   = { fg = "#86a9d2" }
hovered = { fg = "#dcdccc", bg="#4e5c5d" }

# Which
[which]
cols            = 3
mask            = { bg = "#2b2b2b" }
cand            = { fg = "#f0dfaf" }
rest            = { fg = "#8cd0d3" }
desc            = { fg = "#f0dfaf" }
separator       = " ➜ "
separator_style = { fg = "#7f9f7f" }

# Confirm
[confirm]
border  = { fg = "#ace0e3" }
title   = { fg = "#86a9d2" }
content = {}
list    = {}
btn_yes = { bg = "#4e5c5d" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#86a9d2" }
title   = { fg = "#86a9d2" }

# Notify
[notify]
title_info  = { fg = "#ace0e3" }
title_warn  = { fg = "#8cd0d3" }
title_error = { fg = "#8c5353" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#cc9393" }
run     = { fg = "#f0dfaf" }
hovered = { bg = "#5f5f5f" }
footer  = { fg = "#dcdccc", bg = "#4f4f4f" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#8cd0d3" },

	# Media
	{ mime = "{audio,video}/*", fg = "#f0dfaf" },

	# Archives
	{ mime = "application/*zip", fg = "#94bff3" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#94bff3" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#f0dfaf" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#94bff3" },

	# Special files
	{ name = "*", is = "orphan", bg = "#94bff3" },
	{ name = "*", is = "exec"  , fg = "#cc9393" },

	# Fallback
	{ name = "*/", fg = "#8cd0d3" }
]
    